apiVersion: v1
kind: Secret
metadata:
  name: ftp-secret
type: Opaque
data:
  # FTP 서버 주소, 포트, 사용자, 비밀번호, 경로를 Base64로 인코딩하여 저장
  # 실제 값은 'YOUR_VALUE' 부분을 Base64 인코딩한 문자열로 대체
  ftp.server: "ZGV2Lm1hY2Fjb2xhYnMuc2l0ZQ==" # dev.macacolabs.site
  ftp.port: "MjE=" # 21
  ftp.user: "bW9tbmVjdA==" # your_ftp_username
  ftp.password: "bW9tbmVjdA==" # your_ftp_password
  ftp.path: "LzI=" # /2
