server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://elasticsearch-service:9200
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

ftp:
  base-url: ${FTP_FILE_SERVER_URL}

eureka:
  instance:
    hostname: product-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

# swagger
springdoc:
  packages-to-scan: com.momnect.productservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
