apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: juhuiya/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 150
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3