apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  type: ClusterIP